<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>56ae9ec8-577b-4c58-8a01-0af2dbcbdbdd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Properties\launchSettings.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="ModelContextProtocol.AspNetCore" Version="1.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AspNetCore.MCP.BAL\AspNetCore.MCP.BAL.csproj" />
    <ProjectReference Include="..\AspNetCore.MCP.DAL\AspNetCore.MCP.DAL.csproj" />
    <ProjectReference Include="..\AspNetCore.MCP.Domain\AspNetCore.MCP.Domain.csproj" />
  </ItemGroup>

</Project>
